write a readme
electron/electron-frameworks pull request #3
Opened 2017-07-26 17:10 UTC by zeke

This PR adds a README so folks know what this repo is for and how to keep it up to date.

2017-07-26 17:13 UTC, joshaber requested changes
Just a couple notes 🗒

2017-07-26 17:13 UTC, joshaber commented on README.md
> +- [Mantle](https://github.com/Mantle)
This is really https://github.com/Mantle/Mantle

2017-07-26 17:13 UTC, joshaber commented on README.md
> +- [Squirrel](https://github.com/squirrel)
And this is specifically Squirrel.Mac: http://github.com/Squirrel/Squirrel.Mac/

2017-07-26 17:19 UTC, zeke commented on README.md
> +- [Mantle](https://github.com/Mantle)
gotcha. fixed.

2017-07-26 17:22 UTC, joshaber approved these changes

2017-07-31 01:40 UTC, zcbenz approved these changes

2017-07-31 02:51 UTC, merged